name: abeul_planner
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  ## NoSQL DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  ## 상태관리
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:

  uses-material-design: true
