name: abeul_planner
description: "아블 플래너"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  shared_preferences: ^2.5.3
  characters: ^1.4.0
  package_info_plus: ^8.3.0
  webview_flutter: ^4.13.0

  ## NoSQL DB
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  ## 상태관리
  flutter_riverpod: ^2.6.1
  path_provider: ^2.1.5

  ## 앱 아이콘 / 스플래쉬
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.15

flutter:

  uses-material-design: true

  assets:
    - assets/icon/Abeul_Planner_Logo.png
    - assets/privacy_policy.html

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/Abeul_Planner_Logo.png"
  remove_alpha_ios: true
  background_color: "#F1DBDB" # 코랄 핑크
  adaptive_icon_background: "#F1DBDB"
  adaptive_icon_foreground: "assets/icon/Abeul_Planner_Logo.png"

flutter_native_splash:
  color: "#F1DBDB"
  image: assets/icon/Abeul_Planner_Logo.png
  android: true
  ios: true
