# GitHub Actions 워크플로 이름
name: Flutter CI

# 워크플로 실행 조건 설정
on:
  push:
    branches: [master]         # master 브랜치에 push 될 때 실행
  pull_request:
    branches: [master]         # master 브랜치로 PR이 생성될 때 실행

jobs:
  build:                     # 작업(job)의 이름
    runs-on: ubuntu-latest   # 최신 우분투 환경에서 실행 (GitHub에서 제공)

    steps:                   # 작업을 구성하는 단계들
      # GitHub 저장소의 코드를 체크아웃 (가져오기)
      - uses: actions/checkout@v3

      # Flutter 설치 (subosito/flutter-action 사용)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.1'   # 사용할 Flutter 버전 명시

      # 의존성 설치 (pubspec.yaml에 정의된 패키지들)
      - name: Install dependencies
        run: flutter pub get

      # 코드 정적 분석 (문법 및 스타일 오류 체크)
      - name: Analyze
        run: flutter analyze

      # 테스트 실행 (test 폴더 내 테스트 코드 실행)
      - name: Run tests
        run: flutter test

      # 릴리즈용 APK 빌드 (build/app/outputs/flutter-apk/app-release.apk 생성)
      - name: Build APK
        run: flutter build apk --release
